#ifndef  __USR_H__
#define  __USR_H__
#include <hsf.h>
/// <summary>
/// 链接路由器参数是否配置完毕
/// </summary>
int is_connect_to_router(void);
/// <summary>
/// 链接到路由器
/// </summary>
int connect_to_router(void);
/// <summary>
/// 字符串转数组
/// </summary>
void HexStrToByte(const char* source, unsigned char* dest, int sourceLen);
/// <summary>
/// 链接到服务器
/// </summary>
int connect_to_server(void);
/// <summary>
/// 链接服务器参数是否配置完毕
/// </summary>
int is_connect_to_server(void);
/// <summary>
/// 模块工作模式
/// </summary>
int get_work_mode(void);
/// <summary>
/// SOCKB是否连接服务器成功
/// </summary>
int is_sockb_connect(void);
/// <summary>
/// SOCKB链接服务器
/// </summary>
int sockb_connect_to_server(void);
/// <summary>
/// 设置工作模式
/// </summary>
int set_work_mode(void);
/// <summary>
/// 进入透传模式
/// </summary>
int enter_throut_mode(void);
/// <summary>
/// 重启设备
/// </summary>
void restart_device(void);
/// <summary>
/// 封装电陶协议
/// </summary>
void proSendWrapper(uint16_t pack_decs,uint16_t msg_type,uint8_t* msg,uint8_t msg_len);
#endif
